### ISSUE TITLE
error of boost when building the code

### ISSUE THREAD

**Issue by GH-HOME** [tflsguoyu/layeredbsdf#1]
Hi, I face these error when building the code on ubuntu, that seems related to boost. But I have already installed libboost-dev. Any ideas?

`build/release/libcore/libmitsuba-core.so: undefined reference to `boost::this_thread::hidden::sleep_until(timespec const&)'
collect2: error: ld returned 1 exit status
scons: *** [build/release/mitsuba/mtssrv] Error 1
build/release/libcore/libmitsuba-buildcore.so:/ releaseundefined/ libcorereference/ libmitsubato- core.so`:boost :undefined: this_threadreference: :tohidden :`:boostsleep_until:(:timespecthis_thread :const:&hidden):':
sleep_until(timespec const&)'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
scons: *** [build/release/mitsuba/mtsutil] Error 1
scons: *** [build/release/mitsuba/mitsuba] Error 1
scons: building terminated because of errors.`

**Comment by GH-HOME** [comment]
Actually, I can successfully build mitsuba 0.5.0 with current environment, the libboost version is 1.58, could you tell me your building environment?

**Comment by tflsguoyu** [comment]
![image](https://user-images.githubusercontent.com/8923714/54337175-552aa500-45eb-11e9-89c6-5c52e5ab7226.png)
This is what I am currently using.

**Comment by GH-HOME** [comment]
<img width="990" alt="WeChat Screenshot_20190314163856" src="https://user-images.githubusercontent.com/18206839/54339268-b5ffbf00-4677-11e9-8279-0f0e557c2341.png">
odd, actually our environment are same. Can you compile by 'Scons' ?

**Comment by GH-HOME** [comment]
![image](https://user-images.githubusercontent.com/18206839/54339478-52c25c80-4678-11e9-82ea-c66e48756695.png)

Here is the building process of official mitsuba lib.

**Comment by GH-HOME** [comment]
Here is the error when building the layer BSDF
![image](https://user-images.githubusercontent.com/18206839/54339617-bea4c500-4678-11e9-86e8-6697a70931a3.png)

**Comment by tflsguoyu** [comment]
![image](https://user-images.githubusercontent.com/8923714/54339898-5eb80b00-45f3-11e9-8e1c-1734f7d14754.png)
I updated all the libs (sudo apt update && apt upgrade), and recompiled it, still works.

Another way is to copy files to original Mitsuba and add # XXXX to corresponding "SConscript" files.

/include/mitsuba/render/bsdf.h
/include/mitsuba/render/medium.h
/src/librender/bsdf.cpp
/src/bsdfs/roughdielectric.cpp
/src/medium/homogeneous.cpp
/src/medium/homogeneous_aniso.cpp # plugins += env.SharedLibrary('homogeneous_aniso', ['homogeneous_aniso.cpp'])
/src/bsdfs/multilayered.cpp        # plugins += env.SharedLibrary('multilayered', ['multilayered.cpp'])
/src/integrator/path/path_layered.cpp   # plugins += env.SharedLibrary('path_layered', ['path/path_layered.cpp'])

**Comment by GH-HOME** [comment]
Finally, finally, finally, I find the bug!!!!!!

Just related to C++ 11 feature.

If anyone meets the same problem, please change the following code in build/Sconscript.configure
`env.Append(CPPFLAGS=['-std=c++0x'])`

BTW, I appreciate author can help me test the code. Thank you.

**Comment by tflsguoyu** [comment]
Great!

But this flag has already been included in config.py?
